name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch full history to avoid shallow clone

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Extract version from tag
      id: extract_version
      run: echo "##[set-output name=VERSION;]${GITHUB_REF#refs/tags/v}"

    - name: Set version in .csproj
      run: sed -i 's|<Version>.*</Version>|<Version>${{ steps.extract_version.outputs.VERSION }}</Version>|' JoanComas.ScenarioUnitTesting/JoanComas.ScenarioUnitTesting.csproj

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Pack the project
      run: dotnet pack JoanComas.ScenarioUnitTesting/JoanComas.ScenarioUnitTesting.csproj --configuration Release --no-build -o ./artifacts /p:PackageVersion=${{ steps.extract_version.outputs.VERSION }}

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./artifacts/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

    - name: Create Git tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag ${{ steps.extract_version.outputs.VERSION }}
        git push origin ${{ steps.extract_version.outputs.VERSION }}
