name: Publish NuGet Package - JoanComas.ScenarioUnitTesting

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'version-update-net')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Setup NuGet CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y nuget

    - name: Extract version from .csproj
      id: extract_version
      run: |
        VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" JoanComas.ScenarioUnitTesting/JoanComas.ScenarioUnitTesting.csproj)
        echo "Extracted version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Pack the project using NuGet
      run: |
        nuget pack JoanComas.ScenarioUnitTesting.nuspec -Version ${{ env.VERSION }} -OutputDirectory ./artifacts

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: nuget push ./artifacts/*.nupkg -ApiKey $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
