name: Set Version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update version in .csproj file
        run: |
          sed -i "s|<Version>.*</Version>|<Version>${{ env.VERSION }}</Version>|" JoanComas.ScenarioUnitTesting/JoanComas.ScenarioUnitTesting.csproj
          sed -i "s|<version>.*</version>|<version>${{ env.VERSION }}</version>|" JoanComas.ScenarioUnitTesting.nuspec

      - name: Create new branch
        run: |
          git checkout -b version-update-${{ env.VERSION }}
          git add JoanComas.ScenarioUnitTesting/JoanComas.ScenarioUnitTesting.csproj
          git add JoanComas.ScenarioUnitTesting.nuspec
          git commit -m "Update version to ${{ env.VERSION }}"
          git push origin version-update-${{ env.VERSION }}

      - name: Create version-update label if not exists
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh label create version-update --description "Label for version updates" || echo "Label already exists"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Update version to ${{ env.VERSION }}" \
                       --body "This PR updates the version number to ${{ env.VERSION }}." \
                       --head version-update-${{ env.VERSION }} \
                       --base main \
                       --label version-update
